Allow arbitrary commands before and after tests
kolloch/crate2nix pull request #193
Opened 2021-05-05 03:44 UTC by Fuuzetsu

An immediate use-case is to inject any environment variables that the
test may be relying on, such as location of some external files
or overriding some behaviour.

Another, perhaps more cliche use-case is for unsetting the `-e` bash
flag: this will allow us to capture output of failing tests without
giving up on expression itself. In this way, it fixes #191.

2021-05-05 03:46 UTC, Fuuzetsu commented
I verified that I can deal with #191 just by doing

```
testPreRun = "set +e";
testPostRun = "set -e";
```

I also verified that when neither of these flags is set, I don't have any rebuild of the tests so any existing users should not be affected by the change.

2021-06-07 00:05 UTC, Fuuzetsu commented
@kolloch Any updates? It'd be cool if we could use the repo directly rather than our fork. We've been using this change for a while with success.

2021-06-07 11:25 UTC, kolloch requested changes
This looks simple and good. Thank you.

Could you document this in the README.md please and regenarate generated sources by executing `run_tests.sh`? (sorry, this will download the internet)

2021-06-07 11:25 UTC, kolloch commented on crate2nix/templates/nix/crate2nix/default.nix
> +          # get a spurious rebuild unless they set these.
Thank you for being that diligent!

2021-06-08 00:15 UTC, Fuuzetsu commented
>Could you document this in the README.md please and regenarate generated sources by executing run_tests.sh? (sorry, this will download the internet)

Done. All tests passed apparently. I committed the changes. I fixed small typo/grammar issue in the comment, nothing major.

Feel free to change the README.md sections as you see fit if you imagined something a bit different.

2021-06-08 10:45 UTC, kolloch approved these changes
Thank you :)

2021-06-08 10:45 UTC, merged